from other_func import *

states = ['alabama', 'alaska', 'alberta', 'arizona', 'arkansas', 'british columbia', 'california', 
 'colorado', 'connecticut', 'delaware', 'florida', 'georgia', 'hawaii', 'idaho', 'illinois', 
 'indiana', 'iowa', 'kansas', 'kentucky', 'louisiana', 'maine', 'manitoba', 'maryland', 
 'massachusetts', 'michigan', 'minnesota', 'mississippi', 'missouri', 'montana', 'nebraska', 
 'nevada', 'new brunswick', 'new hampshire', 'new jersey', 'new mexico', 'new york', 
 'newfoundland and labrador', 'north carolina', 'north dakota', 'nova scotia', 'ohio', 
 'oklahoma', 'ontario', 'oregon', 'pennsylvania', 'prince edward island', 'quebec', 
 'rhode island', 'saskatchewan', 'south carolina', 'south dakota', 'tennessee', 'texas', 
 'utah', 'vermont', 'virginia', 'washington', 'west virginia', 'wisconsin', 'wyoming']

route_data_keys = {
        "permit_info", "price", "start_date", "use_tolls", "state_fee",
        "other_fee", "service_fee", "attached_at", "state_id", "permit_status",
        "permit_link", "route_image", "route_url", "state_name"
    }

months = ["january", "february", "march", "april", "may", "june", 
              "july", "august", "september", "october", "november", "december"]

# Key-to-function mapping
key_to_function = {
    "order_id": fetch_order_id,
    "token": fetch_token,
    "axle_spacing": fetch_axle_spacing,
    "order_status": fetch_order_status,
    "estimatedTotalCostValue": fetch_estimated_cost_value,
    "Trailer_Type": fetch_trailor_type,
    "axle_weight": fetch_axle_weight,
    "pickup_Address": fetch_pickup_address,
    "delivery_Address": fetch_delivery_address,
    "order_created_date": fetch_order_created_date,
    "permitcount": fetch_permitcount,
    "totalPaidAmount": fetch_total_paid_amount,
    "total_due": fetch_total_due,
    "state_name": fetch_state_name,
    "permit_status": fetch_permit_status,
    "permit_info": fetch_permit_info,
    "state_fee": fetch_state_fee,
    "price": fetch_price,
    "client_name": fetch_client_name,
    "client_id": fetch_client_id,
    "client_phone": fetch_client_phone,
    "driver_name": fetch_driver_name,
    "driver_phone": fetch_driver_phone,
    "driver_id": fetch_driver_id,
    "truck_id": fetch_truck_id,
    "truck_year": fetch_truck_year,
    "truck_make": fetch_truck_make,
    "truck_model": fetch_truck_model,
    "truck_vin": fetch_truck_vin,
    "truck_license_plate": fetch_truck_license_plate,
    "registration": fetch_truck_registration,
    "truckReg_exp": fetch_truck_reg_exp,
    "license_state": fetch_license_state,
    "truck_axle": fetch_truck_axle,
    "carrier_name": fetch_carrier_name,
    "trailer_id": fetch_trailer_id,
    "trailer_model": fetch_trailer_model,
    "trailer_year": fetch_trailer_year,
    "trailer_vin": fetch_trailer_vin,
    "trailer_license_plate": fetch_trailer_license_plate,
    "state": fetch_state,
    "trailer_length": fetch_trailer_length,
    "trailer_type": fetch_trailer_type,
    "trailer_make": fetch_trailer_make,
    "trailer_axle": fetch_trailer_axle,
    "trailer_axle_type": fetch_trailer_axle_type,
    "totalWeight": fetch_totalWeight,
    "order_id": fetch_order_id,
    "other_fee": fetch_other_fee,
    "service_fee": fetch_service_fee,
    "route_url": fetch_route_url,
    "client_email": fetch_client_email,
    "driver_email": fetch_driver_email,
    "commodityDataAndDimension": fetch_commodityDataAndDimension,
    "comlength": fetch_length,
    "comwidth": fetch_width,
    "comheight": fetch_height,
    "comm_weight": fetch_weight,
    "make": fetch_make,
    "model": fetch_model,
    "description": fetch_description,
    "pickup_date": fetch_pickup_date,
    "length": fetch_length,
    "width": fetch_width,
    "height": fetch_height,
    "weight": fetch_weight,
    "make": fetch_make,
    "model": fetch_model,
    "description": fetch_description,
    "overalltrucktrailer": fetch_overalltrucktrailer,
    "overalllength": fetch_overalllength,
    "overallwidth/wide": fetch_overallwidth,
    "overallheight/tall": fetch_overallheight,
    "front_overhang": fetch_front_overhang,
    "rear_overhang": fetch_rear_overhang,
    "OverallOrderData": fetch_OverallOrderData,
    "totalWeight": fetch_totalWeight,
    "overall_route_maplink": fetch_overall_route,
    "invoice": fetch_invoice
}

